# Generated by Django 4.2 on 2024-05-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appG7', '0002_sesion_sala_profile_opinionsala'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='autor',
            field=models.CharField(default='Desconocido', max_length=30),
        ),
    ]
