# Generated by Django 4.2 on 2024-05-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appG7', '0004_auto_20240520_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='avatar.jpg', upload_to='profile_pics'),
        ),
    ]
