# Generated by Django 4.2 on 2024-05-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appG7', '0005_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
