# Generated by Django 4.2 on 2024-07-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appG7', '0006_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='link',
            field=models.CharField(default='link', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='avatar.jpg', upload_to='profile_pics'),
        ),
    ]
