# Generated by Django 3.2.25 on 2024-07-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appG7', '0007_sesion_link_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='ramo',
            field=models.CharField(choices=[('ma1101', 'MA1101'), ('ma1001', 'MA1001'), ('fi1000', 'FI1000'), ('bt1211', 'BT1211'), ('ma1102', 'MA1102'), ('ma1002', 'MA1002'), ('fi1100', 'FI1100'), ('cc1002', 'CC1002'), ('iq2211', 'IQ2211'), ('fi2001', 'FI2003'), ('ma2001', 'MA2001'), ('in2201', 'IN2201'), ('iq2212', 'IQ2212'), ('fi2002', 'FI2002'), ('ma2002', 'MA2002'), ('fi2004', 'FI2004')], max_length=6),
        ),
    ]
