# Generated by Django 3.2.25 on 2024-07-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appG7', '0008_alter_sesion_ramo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='ramo',
            field=models.CharField(choices=[('MA1101', 'MA1101'), ('MA1001', 'MA1001'), ('FI1000', 'FI1000'), ('BT1211', 'BT1211'), ('MA1102', 'MA1102'), ('MA1002', 'MA1002'), ('FI1100', 'FI1100'), ('CC1002', 'CC1002'), ('IQ2211', 'IQ2211'), ('FI2001', 'FI2003'), ('MA2001', 'MA2001'), ('IN2201', 'IN2201'), ('IQ2212', 'IQ2212'), ('FI2002', 'FI2002'), ('MA2002', 'MA2002'), ('FI2004', 'FI2004')], max_length=6),
        ),
    ]
