# Generated by Django 4.2 on 2024-07-16 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appG7', '0009_alter_sesion_ramo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='members',
            field=models.ManyToManyField(related_name='sesiones_as_member', through='appG7.Member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='id_host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_as_host', to='appG7.sesion'),
        ),
        migrations.AlterField(
            model_name='opinionuser',
            name='puntualidad',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')]),
        ),
        migrations.AlterField(
            model_name='opinionuser',
            name='respeto',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')]),
        ),
    ]
