# Generated by Django 4.2 on 2024-07-16 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appG7", "0010_sesion_members_alter_member_id_host_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="id_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
